name: ResourceWorld
main: jp.azisaba.main.resourceworld.ResourceWorld
version: 1.1.1
author: siloneco
description: "Auto regenerate resource world."
softdepend: [WorldEdit, FastAsyncWorldEdit]
api-version: 1.13
commands:
  resourceworld:
    aliases: ["rw", "resourcew", "rworld"]
    usage: "/{LABEL} [recreate]"
    permission: resourceworld.command.resourceworld
    permission-message: You dont have permission to perform this command.
permissions:
  resourceworld.command.resourceworld:
    default: op
  resourceworld.centerprotect.bypass:
    default: op